import { Toaster } from "react-hot-toast";
import "./globals.css";
import { SocketProvider } from "@/context/SocketProvider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SocketProvider>

        {children}
        <Toaster position="top-right" />
        </SocketProvider>
      </body>
    </html>
  );
}
